version: '2'
services:

  web:
    build: ./web
    ports:
     - "8080:8080"

  socket:
    build: ./socket
    ports:
     - "8081:8081"
    depends_on:
     - db
    networks:
     - back

  db:
    build: ./db
    ports:
     - "5432"
    networks:
     - back

networks:
  back:
    driver: bridge
