version: '2'
services:

  web:
    build: ./web
    ports:
     - "8080:8080"

  websocket:
    build: ./websocket
    ports:
     - "8081:8081"
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
#    networks:
#     - back

  db:
    build: ./db
    ports:
     - "5432"
    networks:
     - back

networks:
  back:
    driver: bridge
